version: "3.8"

services:
  # Service Redis
  redis:
    image: redis:alpine
    container_name: my_redis_dev
    ports:
      - "6379:6379" # Mở cổng 6379 để server kết nối vào
    volumes:
      - redis_data:/data # Lưu dữ liệu để tắt đi bật lại không mất
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD} # Sử dụng biến môi trường từ file .env.dev

  # Service Server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_server_dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
volumes:
  redis_data:
