export const Message = {
  PostFound: "Post found",
  PostNotFound: "Post not found",
  PostCreated: "Post created successfully",
  PostUpdated: "Post updated successfully",
  PostDeleted: "Post deleted successfully",
  PostNotDeleted: "Post not deleted",
  PostNotUpdated: "Post not updated",
  PostNotCreated: "Post not created",
  UserFound: "User found",
  UserNotFound: "User not found",
  UserCreated: "User created successfully",
  InternalServerError: "Internal server error",
  CommentFound: "Comment found",
  CommentNotFound: "Comment not found",
  CommentCreated: "Comment created successfully",
  CommentUpdated: "Comment updated successfully",
  CommentDeleted: "Comment deleted successfully",
  CommentNotDeleted: "Comment not deleted",
  CommentNotUpdated: "Comment not updated",
  CommentNotCreated: "Comment not created",
  USER_ALREADY_EXISTS: "User already exists",
  USER_REGISTERED_SUCCESSFULLY: "User registered successfully",
  LOGIN_SUCCESS: "Login successful",
  INVALID_CREDENTIALS: "Invalid credentials",
  WRONG_LOGIN: "Email hoặc mật khẩu không chính xác",
};
